### ISSUE TITLE
Generating profile badges

### ISSUE THREAD

**Issue by pktiuk** [Git-to-know-me/gtkm-server#1]
It would be good to provide simple badges for users which could be embedded in other sites.

Similar to:  
https://github.com/anuraghazra/github-readme-stats

**Comment by mpfmorawski** [comment]
I would like to solve this task. Please assign me to this Issue, @pktiuk.

**Comment by mpfmorawski** [comment]
I would like to create profile badge using [Pillow](https://pillow.readthedocs.io/en/stable/). But I am open to your suggestions for other libraries.

As an MVP, I would like to create a 512 x 256 pixel file. Which would contain:

- static background with GTKM logo
- username
- user profile photo
- number of repos
- number of stars
- number of forks

**Comment by pktiuk** [comment]
Could cou paste here example badge?   
For reference how it is supposed to look

**Comment by mpfmorawski** [comment]
Yes, I prepared the draft of the profile badge. I would appreciate your feedback (especially @pktiuk  and @kamilwil)
 
![GTKM Profile Badge](https://user-images.githubusercontent.com/62252131/184353266-a2b5894c-4d14-4d88-97bd-97f3eacffe8c.png)

**Comment by pktiuk** [comment]
I think Pillow is fine for this purpose.  

In terms of content I think number of repos is not an important measure of anything.

**Comment by pktiuk** [comment]
Example looks fine, but I think it would be better to have longer (and more descriptive) descriptions   
Stars- which stars? Stars collected, or stars given?  

![GitHub stats](https://github-readme-stats.vercel.app/api?username=pktiuk&show_icons=true&theme=github_dark)

In my opinion stats from this example are meaningful and well descriptive

**Comment by pktiuk** [comment]
Anyway as a additional task you should think about some way of simple cashing of generated pictures to aviod generating them every time a request arrives (it can be done as a separate issue)

**Comment by mpfmorawski** [comment]
I am uploading another version of the profile badges prototype. I added colors from the app's color palette and made the stats names more descriptive. In this phase of work, I would like to focus on these three data (repositories, forks, stars) as they are aggregated in our application. When we develop other areas of the app more, that's when we'll be able to put other data on profile badges.

At this point, my goal is to realize this version of the MVP so that we can expand it later.

![GTKM Profile Badge (1)](https://user-images.githubusercontent.com/62252131/185098429-d3904930-0823-4d72-847a-ba53005e356a.png)

**Comment by kamilwil** [comment]
I think "number of" in this case is a bit redundant and takes space unnecessarily. I'd rather go for "Public repos owned", "Forks executed (or smth similar)" and "Stars earned".

Other than that, it looks nice and coherent to me. Maybe keeping some margin around the logo as well could make the badge a little easier on the eye, but it's my subjective preference.

**Comment by mpfmorawski** [comment]
I corrected the stats descriptions based on @kamilwil's comment. I am uploading the current design.

![GTKM Profile Badge (3)](https://user-images.githubusercontent.com/62252131/185109258-35137b16-2608-45ba-af4e-623565130648.png)

**Comment by kamilwil** [comment]
That is exactly what I meant. Thanks!

Still not 100% sure about the logo placed so tightly in the corner, but I'm aware it is not that important here and it might be rightfully treated as nitpicking. :D
